### ISSUE TITLE
[Suggestion] - Compile instructions

### ISSUE THREAD

**Issue by joanbono** [jas502n/BurpSuite_Pro_v1.7.32#1]
Hi man! 

First of all, thanks for your work!
Since your code is not obfuscated, can you upload it and also add compile instructions?

It would be nice!

Thanks again! 👍

**Comment by joanbono** [comment]
Hi @jas502n , any updates on this?

**Comment by pbafe** [comment]
Hi! 
I'm also interested on this! :D

Many thanks for the contribution :+1:

**Comment by joanbono** [comment]
Hi @jas502n any update on this?

**Comment by joanbono** [comment]
Hi @jas502n please could you provide any update on this?

**Comment by joanbono** [comment]
Hi @jas502n , if you are not going to provide compiling instructions or you don't know how to do it, please close the issue. Thaks.

**Comment by joanbono** [comment]
Thanks anyway.
