### ISSUE TITLE
Burp couldn't work properly

### ISSUE THREAD

**Issue by rjosodtssp** [jas502n/BurpSuite_Pro_v1.7.32#3]
I use java.exe in PyCharm, when I run the command `java -jar`, I got a warning
![default](https://user-images.githubusercontent.com/11205685/40781555-e71a3fde-650e-11e8-83ea-4a8de380e87f.png)

Burp is licensed, but when I open the Intercept tab
![default](https://user-images.githubusercontent.com/11205685/40781601-126b8e72-650f-11e8-8f35-d974380f6b5d.png)
only `Raw` and `Hex`, is this caused by java's version ?

**Comment by joanbono** [comment]
That's the normal behavior.

Under **Intercept**, Burp only have `Raw` and `Hex`.

The warning just notifies you that Burp is not tested in your JRE version, and is not Optimized and MAY cause problems, but I've been using Burp in a non-Tested JRE and never had a problem.

Thanks

**Comment by joanbono** [comment]
Hi @rjosodtssp can you close the issue if you have any other question?
